### ISSUE TITLE
You could get away with albedo support at this point

### ISSUE THREAD

**Issue by Sunconure11** [jellysquid3/phosphor-forge#36]
https://www.curseforge.com/minecraft/mc-mods/albedo?gameCategorySlug=mc-mods&projectID=275300

Open source now as well

**Comment by jellysquid3** [comment]
This is very interesting now that the source code has been made public and definitely warrants looking into. Thanks for the heads-up.

**Comment by jellysquid3** [comment]
Phosphor for Minecraft 1.12 is no longer supported and will not receive additional updates outside of those for maintenance sake.
