### ISSUE TITLE
NPE in LightingEngine.getCursorCachedLight()

### ISSUE THREAD

**Issue by LemADEC** [jellysquid3/phosphor-forge#50]
As of phosphor-1.12.2-0.2.6+build50, our dedicated server had an NPE crash:
```
[10:47:00] [Server thread/INFO] [warpdrive]: TileEntityShipCore 'SS ButtPirate MkII' @ xxx (xxx) Connected, IDLE, Enabled, 0 controllers, warm-up
0, cool down 0
[10:47:06] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
>       at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.getCursorCachedLight(LightingEngine.java:576) ~[LightingEngine.class:?]
>       at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdatesForTypeInner(LightingEngine.java:300) ~[LightingEngine.class:?]
>       at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdatesForType(LightingEngine.java:189) ~[LightingEngine.class:?]
>       at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdates(LightingEngine.java:164) ~[LightingEngine.class:?]
>       at net.minecraft.world.gen.ChunkProviderServer.handler$onSaveChunks$bcd000(ChunkProviderServer.java:1532) ~[on.class:?]
>       at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java) ~[on.class:?]
>       at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:4783) ~[oo.class:?]
>       at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:574) ~[WorldManager.class:1.12.2-2838-7.1.7-RC3928]
>       at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:4656) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.constant$getSaveTickInterval$zjm000(MinecraftServer.java:4603) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:687) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[10:47:06] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/wwm/wwm/./crash-reports/crash-2019-11-10_10.47.06-server.txt
[10:47:06] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[10:47:06] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
```

Crash report is https://gist.github.com/LemADEC/ccb11b13da5f18e3a87b8a443e27dfcc

**Comment by jellysquid3** [comment]
Please upload the server debug log file found in the `logs` folder of your server's root folder. It should be named `fml-server-debug.log` or `debug.log`.

**Comment by LemADEC** [comment]
That's a competitive server, I would need to cut most of it to protect their base coordinates.

**Comment by LemADEC** [comment]
Here's the edited version https://gist.github.com/LemADEC/26b6cc6a74c9953945cbb8ef1772462f
I've added another crash report to the first one

**Comment by jellysquid3** [comment]
I'm not certain why this crash occurred... it's new to me. The crash pinpoints that the chunk Phosphor obtained from the server world's `IChunkProvider` is null, but this is not valid behaviour for that interface in the game and indicates a serious problem outside Phosphor.

Alternatively, it is possible that something in the game is violating the thread safety contract of the World class. This can happen if you install certain mods or patches, but as far as I can tell the code on our side for detecting this is sound and would have caught and prevented it.

Please verify that you have disabled Sponge's Asynchronous Lighting patches in your configuration files for SpongeForge; it may be the cause of the problem.

**Comment by LemADEC** [comment]
Sponge async lighting is disabled. It's been broken for several months now.

As for the missing chunk here, it would help to have a dump of whatever information are available (world object class, world name & id, chunk coordinates, etc.). There's a few mods that use sub/fake worlds, should be easy to catch from the world object details.

**Comment by jellysquid3** [comment]
Phosphor for Minecraft 1.12 is no longer supported and will not receive additional updates outside of those for maintenance sake.
