### ISSUE TITLE
1.14 is currently is only listing the fabric version

### ISSUE THREAD

**Issue by Winddbourne** [jellysquid3/phosphor-forge#65]
As the title says the 1.14 forge version of Phosphor seems to be missing. I can find it in 1.12 and in 1.15, but . . . 

![phosphor](https://user-images.githubusercontent.com/24589533/78416347-3502c500-75f6-11ea-97aa-5b5f426a46dd.png)

Figure you'd want to know. :)

**Comment by jellysquid3** [comment]
Phosphor does not currently support Minecraft 1.14. There is an older release for the Fabric build, but one was never created for Forge.
