### ISSUE TITLE
Crash on Startup with Stargate Network

### ISSUE THREAD

**Issue by VelociraptorsofSkyrim** [jellysquid3/phosphor-forge#67]
Minecraft auto-crashes when the Stargate Network mod is installed with the latest version.

I press play on the Minecraft Launcher, it closes, and then pops back up saying the Game has crashed, but there is no crashlog in the .Minecraft folder, but this is in the log folder.

[--crash log snipped--](https://gist.github.com/jellysquid3/5fc751a20aa3fbc777e4985515cd3f8b)

I can confirm this only occurs when the latest version of Phosphor installed. Previous versions run perfectly fine and the rest of the mods start up fine without it installed.

**Comment by jellysquid3** [comment]
The latest beta release of Phosphor is only intended for users who have special woes with Mixins 0.8. You do not need to upgrade if the previous release worked fine.

As your game needs Mixins 0.7, Phosphor 0.2.7 crashes. Downgrade to Phosphor 0.2.6.
