### ISSUE TITLE
ColoredLux Support in the future maybe?

### ISSUE THREAD

**Issue by fkrisi11** [jellysquid3/phosphor-forge#71]
Could you guys also add support to this mod, alongside Albedo, please?
https://www.curseforge.com/minecraft/mc-mods/colored-lux

**Comment by eatmyvenom** [comment]
That mod appears to be for 1.12 which is currently no longer supported.

**Comment by Zeitheron** [comment]
@eatmyvenom I actively support 1.12, especially ColoredLux

**Comment by eatmyvenom** [comment]
Sorry my wording must have been confusing, Phosphor is no longer supporting 1.12

**Comment by Zeitheron** [comment]
I mean, @jellysquid3 did tag this as "enhancement" and did not close it with the "1.12 is not supported"
ig something will be done?

**Comment by jellysquid3** [comment]
Phosphor for Minecraft 1.12 is no longer supported and will not receive additional updates outside of those for maintenance sake.
