### ISSUE TITLE
Incompatibility with OpenTerrainGenerator / Other Mixins? Crash on worldgen

### ISSUE THREAD

**Issue by ckhawks** [jellysquid3/phosphor-forge#73]
Phosphor version: `1.12.2-0.2.7`
OTG version: `1.12.2-v8.3` (with Biome Bundle `1.12.2-v6.1`)
Other Mixin mods used (that I know of):
VanillaFix `1.0.10-150`
Surge `1.12.2-2.0.79`
Performant `1.12.2-1.10`

I was trying to see if updating everything to use mixins 0.8 would fix whatever was happening, no dice. I'd greatly appreciate insight and/or direction to somewhere else! <3

Crash log: https://pastebin.com/raw/XSczffkN

**Comment by eatmyvenom** [comment]
Phosphor is no longer being developed or supported in 1.12.
See #71 and https://github.com/jellysquid3/phosphor-forge/issues/64#issuecomment-609088588_

**Comment by ckhawks** [comment]
Got it, I'll remove Phosphor then.
