### ISSUE TITLE
Use Phosphor with 1.14.4

### ISSUE THREAD

**Issue by Razboy20** [jellysquid3/phosphor-forge#75]
Hi, this is probably a stupid question, but I see that you mention Phosphor working for 1.12.2 and for 1.14.4+. How do I get Phosphor to run on 1.14.4?

**Comment by MadHau5** [comment]
Afaik, phosphor only runs on 1.14 using fabric do you'll have to use that instead of forge. Phosphor 1.15 is there for both fabric and forge though.

**Comment by Devan-Kerman** [comment]
phosphor was originally a 1.12 forge mod, iirc jelly ported the fabric versions to forge as well at some point, but I don't remember if it was 1.14 or 1.15

**Comment by MadHau5** [comment]
iirc 1.15-forge exists but 1.14-forge doesn't.

**Comment by jellysquid3** [comment]
See https://github.com/jellysquid3/phosphor-forge/issues/52#issuecomment-617496802. There is no build for Phosphor on Minecraft Forge 1.14.

**Comment by Razboy20** [comment]
🤦‍♂️ Yup, it was a stupid question. Thanks for your quick answer!

**Comment by Devan-Kerman** [comment]
just wondering, why do you play 1.14 instead of 15?

**Comment by Razboy20** [comment]
> just wondering, why do you play 1.14 instead of 15?

That's a good point, mostly for mod compatibility (list of mods), though now I'm realizing that that might not be much of a thing between 1.14.4 and 1.15, though I'll need to check on that.
